module.exports = [
	"I am Tiny.",
	"Tiny here.",
	"Are you ready to rubble?",
	"No stone unturned.",
	"Who breathes life into these old stones?",
	"My stones gather.",
	"Sticks and stones will break their bones!",
	"They call me Tiny.",
	"Tiny!",
	"Hard times coming!",
	"Rockfall coming!",
	"Stay close, Little Roc!",
	"I just mantled.",
	"Thus are mountains built!",
	"I peaked!",
	"Everything’s shrinking.",
	"You can get blood from a stone.",
	"Hard knocks.",
	"Rock bottom.",
	"From gravel to the grave.",
	"To bedrock I return.",
	"Make a henge from my stones.",
	"Returned to sediment.",
	"Stone cold...",
	"A millstone around my neck...",
	"Die hard.",
	"Bigger they are, the harder they fall.",
	"Fly away, Little Roc...",
	"Come back, Little Roc!",
	"Crushed you!",
	"Stone dead.",
	"Here’s a carbon footprint for ya.",
	"You made your bedrock, now die in it.",
	"Knocked ya back to the stone age.",
	"You were as abrasive as sandstone.",
	"You were a sedimental favorite.",
	"You got rocks in your head.",
	"You just fell on hard times.",
	"Don’t carve my headstone yet.",
	"Why do they call it the Mineral Kingdom? We don’t even have a king.",
	"My enemies break upon me like surf upon the stone.",
	"Rock-blocked!",
	"Rocked you.",
	"Stoned you.",
	"Hard luck.",
	"Stony silence...forever.",
	"Victory, etched in stone!",
	"Ha-ha, put up a stone in my honor!",
	"It’s hard to be this good.",
	"You leave Little Roc alone!",
	"The road ahead looks rocky, but that’s all right with me.",
	"I think you bit off more than you can chew, Lifestealer.",
	"My life is too big to be stolen.",
	"I thought you were made of rock like me, but I guess it was only chalk.",
	"Whatever rock you’re made of seems to be delicate stuff.",
	"That’s for all the times you skipped me on the river.",
	"Ha ha ha, sorry, I thought you liked to jump.",
	"When I tell you to jump, I say how high.",
	"Did I put a hole in your hull?",
	"You’re not such a crack shot, Sniper.",
	"Now that’s a stony silence.",
	"Aw, Medusa, I thought you were gonna help me make friends.",
	"What the heck? He’s soft on the inside.",
	"Nothing personal, Ancient. Some of my best friends are fossils.",
	"Rocks have no enemy but time.",
	"First Blood...from a stone. Ha ha ha ha!",
	"First Blood! Better yours than mine.",
	"Ha ha ha! Now you’re really in trouble.",
	"Tusk!",
	"The Tusk!",
	"Ymir!",
	"I am Ymir!",
	"The Tusk is always ready for a fight!",
	"They call me the Terror from the Barrier. They call me the Snowball from Cobalt. But you may call me Tusk!",
	"Who’s ready for a fight? The first hit is free! Anyone?",
	"First blood! And that is how we do things in the north! Ha ha ha ha ha!",
	"That was first blood? I barely touched you! Ha ha ha ha ha ha ha!",
	"First blood! Now who wants to be second?",
	"I have punching for you!",
	"I say we should trade blows!",
	"Get ready! Here I come!",
	"Let us keep this clean.",
	"When you are ready.",
	"Want to try your luck?",
	"You are going nowhere!",
	"Packed special for you!",
	"Snowball!",
	"Snowball fight!",
	"Snow says no!",
	"Well I tried.",
	"Where did they go?",
	"Was worth a try!",
	"That was a big ball of failure.",
	"Well, we’re here.",
	"I will just let you off here.",
	"Mm, a cozy cold.",
	"Love the cold!",
	"Ready!",
	"This next one is gonna sting.",
	"Winding up!",
	"Come at me!",
	"Ready when you are!",
	"Walrus Punch!",
	"Keen Punch!",
	"Oglodi Punch!",
	"Greevil Punch!",
	"Fundamental Punch!",
	"Elemental Punch!",
	"Dire Punch!",
	"Radiant Punch!",
	"Roshan Punch!",
	"Grievous Punch!",
	"Heroic Punch!",
	"Phoenix Punch!",
	"Ozkavosh Punch!",
	"Chaos Punch!",
	"Puck Punch!",
	"Omni Punch!",
	"Shadow Punch!",
	"Phantom Punch!",
	"Lunch Punch!",
	"Icehouse Punch!",
	"Cucumber Punch!",
	"Inclement Punch!",
	"Ultimate Punch!",
	"Magnificent Punch!",
	"My Signature Punch!",
	"Boreal Punch!",
	"Arctic Punch!",
	"Tundra Punch!",
	"Permafrost Punch!",
	"Icy Punch!",
	"Polar Punch!",
	"Galactic Punch!",
	"Orbital Punch!",
	"Onehellofa Punch!",
	"Thesaurical Punch!",
	"That’s the Love Punch!",
	"Love Punch!",
	"Friendship Punch!",
	"Counter Punch!",
	"Thirty Degrees Below Punch!",
	"Penetrating Punch!",
	"Equatorial Punch!",
	"Iceberg Punch!",
	"Icicle Punch! Ooo.",
	"Snowdrift Punch!",
	"Winterfreeze Punch!",
	"Snowflake Punch!",
	"Pudge Punch!",
	"Drunk Punch!",
	"Dragon Punch!",
	"Falcon Punch!",
	"Crocodile Punch!",
	"Another Punch!",
	"And Another Punch!",
	"Punch Punch!",
	"Punch Punch Punch!",
	"Puncha Puncha Puncha!",
	"Horsekick Punch!",
	"Moderately Painful Punch!",
	"Regrettable Punch!",
	"Bug Punch!",
	"Face Punch!",
	"Magnus Punch!",
	"Double Dragon Punch Punch!",
	"Punchdrunk Punch!",
	"Here’s a Bunch of Punches!",
	"Whole Bunch of Punches!",
	"Magus Punch!",
	"Heh! I missed!",
	"That did not go well.",
	"Well there’s your problem.",
	"Upped my weightclass!",
	"I flex! Hmmm!",
	"Ah! A great workout!",
	"A good warmup!",
	"Now the fun begins!",
	"They will not know what hit them.",
	"I dare them to fight me.",
	"That gets my seal of approval!",
	"You've got blood on you.",
	"Stay frosty.",
	"I don't know my own strength!",
	"You were out of your weightclass.",
	"Aww, tough break.",
	"Pack some snow on it. You'll be fine.",
	"Survival of the fittest.",
	"You were all heart. I liked you.",
	"Care to go another round?",
	"I was just getting warmed up!",
	"Down for the count!",
	"Ah ha! Ah! Oh that's good.",
	"I am the Snowball from Cobalt!",
	"That trick won the great brawl at White Fields!",
	"It's just a little snow!",
	"I never pull my punches.",
	"Knockout!",
	"Oh, that had to hurt!",
	"Bang! Zoom! To the Mad Moon!",
	"That was my favorite punch! You were impressed?",
	"That punch has ended more fights than I can remember!",
	"Fist bump!",
	"Now you are old chum.",
	"Hell froze over.",
	"Even you should come in from the cold once in a while.",
	"Only a cruel beast turns one's friends against him.",
	"Did you know that I shatter ice with my fists for fun?",
	"How many were there? Maybe I've had one too many blows to the head!",
	"You should bandage up that belly next time!",
	"Night night, Mr. Dream.",
	"I do not think you're having fun, man-horse!",
	"War is no reason to be unsporting.",
	"Sorry to do that to you darling.",
	"You know I do not mean it, right?",
	"A rematch with me was a bad idea.",
	"You call those tusks? Hm hm!",
	"So are you supposed to be some kind of ice ghost?",
	"I look forward to your kebabs, Magnus.",
	"Break their armor and I will smash them, Slardar.",
	"Just a warmup!",
	"Cool off.",
	"Chill out.",
	"Nice try!",
	"Good practice.",
	"Wimp.",
	"Wimp!",
	"He's a sparrow.",
	"Featherweight.",
	"Fight fair!",
	"Wow! You hit hard.",
	"Oh that smarts!",
	"Got me good...",
	"Good show...",
	"That one hurt...",
	"Coulda been a contender.",
	"Down for the count.",
	"My fight money...",
	"This round is over.",
	"Knocked out.",
	"I threw this one.",
	"This is outrageous.",
	"Glad it was you.",
	"Atta girl.",
	"Isn't she something.",
	"I insist on a rematch!",
	"All right. Sparring is done. We fight for real this time!",
	"I don't know where I was, but it was too warm.",
	"And this will help me punch?",
	"I will hit them with the heavy part. I think.",
	"It's very nice. What does it do?",
	"It's a great day to do some squat thrusts and lift a barrel of fish, is it not?",
	"Battle is battle. Why bet against me?",
	"This fighter never fails.",
	"Refridgeration!",
	"And the winner, by unanimous decision, is me!",
	"I have bloody knuckles and a smile. Now: who wants a drink?",
	"Earthshaker!",
	"Feel the earth shake!",
	"Quiver and quake!",
	"Shake it!",
	"Grounded!",
	"Time to shake things up and see where they settle.",
	"First Blood...and you had better get used to it.",
	"The earth moves under my feet!",
	"Bass and tremble!",
	"Let the earth quake!",
	"Shake it and take it!",
	"I'm gonna pound you!",
	"Earth first!",
	"Earthshaker first!",
	"Quake and crack!",
	"They call me the Fissure Man!",
	"Ground pound!",
	"Slammin'!",
	"Chaos Dunk!",
	"Slammin'...?",
	"Echo Slam...?",
	"Stronger by an order of magnitude.",
	"I am greatly moved.",
	"My heart is pounding.",
	"Did you feel that?",
	"All fall down...",
	"Not my fault...",
	"Stop shaking...",
	"Reduce, reuse, respawn.",
	"The Earth needs me.",
	"The Earth and I rise as one.",
	"No longer will your hooves dig into my hide.",
	"This is no place for a mother.",
	"Pick a different place to raise a family next time.",
	"I'll not bow to you, Sand King, but I liked your style.",
	"Clockworks...and then it doesn't.",
	"Clock-blocked!",
	"Worship that!",
	"Respect the earth...shaker.",
	"Phantom Lancer, I hate all of you.",
	"Divided you fell.",
	"Did the earth move for you too?",
	"There may be many earths, but there's only one Earthshaker.",
	"Shake well and destroy!",
	"Storm Spirit has arrived!",
	"Ha ha! I am here!",
	"Stormy weather...",
	"You had better not start without me!",
	"Draw back the curtains, I'm here!",
	"I'm in a hurry-cane!",
	"Where's the party?",
	"Let the fun begin!",
	"I'm over here!",
	"Over here now!",
	"Here I am!",
	"Puddin' pop!",
	"Ooh, who's that handsome devil?",
	"Looking good!",
	"Get set for heavy weather!",
	"Storm Force Five!",
	"Can't breathe!",
	"I blew it...",
	"I'll fight to the last...breath...",
	"Spirit...away...",
	"You blew it!",
	"Told you a storm was coming!",
	"Blow the man down!",
	"No whining now!",
	"Admiral, but not admirable. Hm hm hm hm.",
	"Call off your little storms, Razor. They're an embarassment.",
	"You shouldn't have spit into the wind, Viper.",
	"Ha ha ha ha. Your maidenly charms were wasted on me.",
	"Antimage, you're no fun at all.",
	"I accept this honor on behalf of storms everywhere!",
	"Everyone complains about the weather... well, I'm doing something about it!",
	"When a warm front and a cold front love each other very much...a storm is born!",
	"I only want blue tangos in my dressing room!",
	"NOOOOOOOOOOOOOOOOOOOOOO!",
	"I'll save this till it's five o'clock... somewhere.",
	"Was that a spotlight? On me?",
	"Such greatness deserves to be shared.",
	"Five targets marked for death.",
	"Nyx assassin.",
	"Assassination is inevitable.",
	"My purpose is clear, my targets doomed.",
	"First blood, heheah hah heh! Nyx, Nyx.",
	"In the name of Nyx, the first assassination is complete.",
	"I skitter, thththt.",
	"On chitinous legs.",
	"I have one purpose for being.",
	"Nyx, Nyx.",
	"My words enter the mind, but not the ear.",
	"Nyx guides me.",
	"As Nyx would have it.",
	"Oh, fleshy.",
	"By Nyx.",
	"In Nyx name.",
	"Chosen of Nyx.",
	"I dig, they die.",
	"Talentless.",
	"You can't run from your thoughts.",
	"Come now, strike me.",
	"Fight, coward.",
	"Strike me, coward.",
	"I failed you, Nyx, I was so close.",
	"I am the pride of Nyx.",
	"Nyx, Nyx, Nyx, Nyx.",
	"Nyx, hehahahha.",
	"You are as dead as they come.",
	"Nyx welcomes you.",
	"Heheahah ahaha haha, Nyx, Nyx, Nyx.",
	"Nyx, Nyx, Nyx, heh heh hah.",
	"Ah, you stupid...",
	"Neither hot, nor cold, just dead.",
	"Not an easy bug to kill, but worth the effort.",
	"Hahahaha! Your books couldn't save you.",
	"Broodmotherfuh...",
	"Ahaha, the undying is dead.",
	"I despises you since the birth of my whole entire caste.",
	"Ah, impressive stinger Sand King, Very sharp, yes.",
	"Your bribe of coin is wasted on Nyx.",
	"Death and gold are linked.",
	"Aheh, Nyx on you.",
	"You've been nyxed.",
	"With my last thought, I curse you.",
	"Oh, Nyx.",
	"I am Nyx, grakillaaghraamghiah! Oi-grayoighaaah… Nyx-aaaagh...",
	"Armorless beings were not meant for life.",
	"It is not my fault. The armorless were not meant for life. Look at them.",
	"Necronomicon. Nice.",
	"Blade mail?",
	"Nyx on that.",
	"Nyx I say.",
	"Chichifchichi.",
	"Nyx chichichichichichi.",
	"Hochichchchchchchichichi.",
	"Hihchchchcichi.",
	"Nyx, heheheh.",
	"Ah, Nyx, thththt.",
	"Nyx, Nyx.",
	"For Nyx.",
	"Ah, Nyx, Nyx, Nyx, Nyx.",
	"The mysteries cannot protect themselves.",
	"Lanaya.",
	"Well that's it. The secret is out!",
	"First blood! There's nothing more mysterious until it has been spilled.",
	"A trail of clues.",
	"In pursuit of the mysteries.",
	"I am driven by secrets!",
	"Tis a secret!",
	"Psi no more!",
	"Trap set!",
	"Oh, snap!",
	"Snap!",
	"Feed me if you must.",
	"Killed by your own hand.",
	"You made a powerful enemy.",
	"You came too close to the secrets.",
	"You'll never know the mysteries.",
	"You never could keep a secret.",
	"The truth is all around you but it hides from the unworthy.",
	"For heresies unknown, the Temple decreed your death.",
	"Secretly, I admired you.",
	"The only mystery is how you lasted so long.",
	"Riki, it's no secret that you're a poor assassin.",
	"Omniknight, your continual braying had to be silenced.",
	"Oh, Spectre, we could have shared such secrets.",
	"I thought you spoke of mysteries but I see you were only confused.",
	"Phantom Assassin, you're not here for me, are you?",
	"Keeping secrets can kill you.",
	"Now you'll never know.",
	"Is that all there is?",
	"Let's keep that between us, all right?",
	"My body is a temple for which I will kill.",
	"It's no secret- I was hoping for one of these.",
	"It's an open secret, obvious to all, that this one is in the bag!",
	"Our secrets now lie bare for the whole world to see.",
	"The mysteries are safe for another day.",
	"Ha. Ha. Ha.",
	"Phantom Assassin!",
	"I'm here to blur the line between life and death.",
	"My list has five names on it.",
	"Have some blade.",
	"Were you expecting me?",
	"Unkind cut!",
	"I feel...blurry!",
	"My edges are running!",
	"I'm soft on the eye.",
	"I'm easy to overlook.",
	"You'll see less of me now.",
	"I'm an immaterial girl!",
	"There's more of me, but less to see.",
	"That went well, I think.",
	"Assassination is nature's way.",
	"Death at my hands is an honor.",
	"Gotta keep my hand in.",
	"I'm not greedy.",
	"Turnabout is foul play!",
	"Don't tell me, I'm a sight for sore eyes.",
	"Queendom come!",
	"There will be pain, there will be screaming.",
	"So begins the reign of pain.",
	"Make way for you Queen.",
	"First blood! Just a little, he he he.",
	"A path to pain.",
	"Does this hurt!",
	"A love bite!",
	"Pain builds charcter.",
	"A little knife play?",
	"Oh! I love your new piercing!",
	"Was it really that bad?",
	"Didn't like the sound of that?",
	"You were weak.",
	"I'm a strong believer in women's suffer-age.",
	"Done already?",
	"My bindings tighten!",
	"I'm a pain specialist.",
	"Did you forget your safe word?",
	"The ecstasy of agony.",
	"You hurt the ones you love.",
	"Night Stalker, you aren't the only thing that goes bump in the night.",
	"Oh, Anti-Mage, I'll make you break your vows.",
	"Crystal Maiden... are you really, I wonder?",
	"Silencer? I'd prefer a screamer.",
	"Bones and no flesh? Where's the pleasure in that?",
	"Submit to your lasy, little girl.",
	"You want me? Come get me.",
	"You can look but don't touch. Come to think of it, don't look either.",
	"Skeleton King, could you feel something for me?",
	"Your pain, my gain.",
	"What a pain in the aaaaaaaa!",
	"I'll be my own successor!",
	"I know I'm a pain, but you love me anyway.",
	"I'm in a world of pain, it's wonderful!",
	"You'll find that I'm all stick and no carrot.",
	"Bottle royale.",
	"You're simply not worthy.",
	"The pain shall set you free, ha ha ha ha ha ha ha ha ha",
	"It feels so good to be bad.",
	"The Moon Rider has arrived.",
	"Nova could use a snack.",
	"Watch over me, Goddess. It'll be a good show.",
	"First blood! For Selemene and for the Dark Moon!",
	"I'll see your entrails.",
	"Let the sky tear down the unworthy!",
	"Hungry, Nova?",
	"Die with honor, whelp.",
	"Aww. Are you not going to beg?",
	"Lost in the woods, are you?",
	"Clearly not your best.",
	"Pathetic.",
	"Not bad for a cat toy.",
	"I'll take your hoof for a trophy.",
	"No princess lives forever, Mirana.",
	"I've waited years to do that.",
	"Don't blame me for being ambitious.",
	"I would water the trees with their entrails if Selemene would smile on me.",
	"Hah! I remember when Nova tried to kill me. Good girl.",
	"Isn't that a pretty thing!",
	"Your Priestess has arrived!",
	"Tuck your tail and run, you mutt!",
	"Bullseye!",
	"Out of my way!",
	"Who spoiled that shot?",
	"Son of a...",
	"Just what are you hiding, Roshan?",
	"I could have hit Roshan with my eyes closed.",
	"Poor Roshan.",
	"Stars, take me!",
	"Lucky shot...",
	"It was not luck, but... skill!",
	"Pathetic whelp.",
	"Seeing stars?",
	"You have learned nothing.",
	"You make a fine crater.",
	"A mounted bow will always claim victory.",
	"Luna, you shouldn't get catty.",
	"Sagan has been eyeing your mount all day.",
	"If you must dominate a beast to your cause, you have already lost.",
	"And now you are kitty litter.",
	"Carl, meet Sagan.",
	"I hope no one here is allergic...to defeat.",
	"Nice kitty...very nice kitty...",
	"Nothing stirs the blood like battle. It's better than catnip!",
	"The cost of kibble.",
	"Sparkles, like the stars."
];
