module.exports = [
	"I am Tiny.",
	"Tiny here.",
	"Are you ready to rubble?",
	"No stone unturned.",
	"Who breathes life into these old stones?",
	"My stones gather.",
	"Sticks and stones will break their bones!",
	"They call me Tiny.",
	"Tiny!",
	"Hard times coming!",
	"Rockfall coming!",
	"Stay close, Little Roc!",
	"I just mantled.",
	"Thus are mountains built!",
	"I peaked!",
	"Everything’s shrinking.",
	"You can get blood from a stone.",
	"Hard knocks.",
	"Rock bottom.",
	"From gravel to the grave.",
	"To bedrock I return.",
	"Make a henge from my stones.",
	"Returned to sediment.",
	"Stone cold...",
	"A millstone around my neck...",
	"Die hard.",
	"Bigger they are, the harder they fall.",
	"Fly away, Little Roc...",
	"Come back, Little Roc!",
	"Crushed you!",
	"Stone dead.",
	"Here’s a carbon footprint for ya.",
	"You made your bedrock, now die in it.",
	"Knocked ya back to the stone age.",
	"You were as abrasive as sandstone.",
	"You were a sedimental favorite.",
	"You got rocks in your head.",
	"You just fell on hard times.",
	"Don’t carve my headstone yet.",
	"Why do they call it the Mineral Kingdom? We don’t even have a king.",
	"My enemies break upon me like surf upon the stone.",
	"Rock-blocked!",
	"Rocked you.",
	"Stoned you.",
	"Hard luck.",
	"Stony silence...forever.",
	"Victory, etched in stone!",
	"Ha-ha, put up a stone in my honor!",
	"It’s hard to be this good.",
	"You leave Little Roc alone!",
	"The road ahead looks rocky, but that’s all right with me.",
	"I think you bit off more than you can chew, Lifestealer.",
	"My life is too big to be stolen.",
	"I thought you were made of rock like me, but I guess it was only chalk.",
	"Whatever rock you’re made of seems to be delicate stuff.",
	"That’s for all the times you skipped me on the river.",
	"Ha ha ha, sorry, I thought you liked to jump.",
	"When I tell you to jump, I say how high.",
	"Did I put a hole in your hull?",
	"You’re not such a crack shot, Sniper.",
	"Now that’s a stony silence.",
	"Aw, Medusa, I thought you were gonna help me make friends.",
	"What the heck? He’s soft on the inside.",
	"Nothing personal, Ancient. Some of my best friends are fossils.",
	"Rocks have no enemy but time.",
	"First Blood...from a stone. Ha ha ha ha!",
	"First Blood! Better yours than mine.",
	"Ha ha ha! Now you’re really in trouble.",
	"Tusk!",
	"The Tusk!",
	"Ymir!",
	"I am Ymir!",
	"The Tusk is always ready for a fight!",
	"They call me the Terror from the Barrier. They call me the Snowball from Cobalt. But you may call me Tusk!",
	"Who’s ready for a fight? The first hit is free! Anyone?",
	"First blood! And that is how we do things in the north! Ha ha ha ha ha!",
	"That was first blood? I barely touched you! Ha ha ha ha ha ha ha!",
	"First blood! Now who wants to be second?",
	"I have punching for you!",
	"I say we should trade blows!",
	"Get ready! Here I come!",
	"Let us keep this clean.",
	"Want to try your luck?",
	"You are going nowhere!",
	"Well I tried.",
	"Where did they go?",
	"Was worth a try!",
	"That was a big ball of failure.",
	"Well, we’re here.",
	"I will just let you off here.",
	"Walrus Punch!",
	"Keen Punch!",
	"Oglodi Punch!",
	"Greevil Punch!",
	"Fundamental Punch!",
	"Falcon Punch!",
	"Crocodile Punch!",
	"Heh! I missed!",
	"That did not go well.",
	"Well there’s your problem.",
	"Upped my weightclass!",
	"I flex! Hmmm!",
	"You've got blood on you.",
	"Stay frosty.",
	"Ah ha! Ah! Oh that's good.",
	"I am the Snowball from Cobalt!",
	"That trick won the great brawl at White Fields!",
	"It's just a little snow!",
	"Oh, that had to hurt!",
	"Bang! Zoom! To the Mad Moon!",
	"That was my favorite punch! You were impressed?",
	"Only a cruel beast turns one's friends against him.",
	"Did you know that I shatter ice with my fists for fun?",
	"How many were there? Maybe I've had one too many blows to the head!",
	"You should bandage up that belly next time!",
	"Night night, Mr. Dream.",
	"I do not think you're having fun, man-horse!",
	"War is no reason to be unsporting.",
	"Sorry to do that to you darling.",
	"You know I do not mean it, right?",
	"A rematch with me was a bad idea.",
	"You call those tusks? Hm hm!",
	"So are you supposed to be some kind of ice ghost?",
	"I look forward to your kebabs, Magnus.",
	"Break their armor and I will smash them, Slardar.",
	"Fight fair!",
	"Wow! You hit hard.",
	"Oh that smarts!",
	"Got me good...",
	"Coulda been a contender.",
	"I threw this one.",
	"This is outrageous.",
	"Glad it was you.",
	"Atta girl.",
	"Isn't she something.",
	"I insist on a rematch!",
	"All right. Sparring is done. We fight for real this time!",
	"I don't know where I was, but it was too warm.",
	"And this will help me punch?",
	"I will hit them with the heavy part. I think.",
	"It's very nice. What does it do?",
	"It's a great day to do some squat thrusts and lift a barrel of fish, is it not?",
	"Battle is battle. Why bet against me?",
	"This fighter never fails.",
	"Refridgeration!",
	"And the winner, by unanimous decision, is me!",
	"I have bloody knuckles and a smile. Now: who wants a drink?",
	"Earthshaker!",
	"Feel the earth shake!",
	"Quiver and quake!",
	"Shake it!",
	"Grounded!",
	"Time to shake things up and see where they settle.",
	"First Blood...and you had better get used to it.",
	"The earth moves under my feet!",
	"Bass and tremble!",
	"Let the earth quake!",
	"Shake it and take it!",
	"I'm gonna pound you!",
	"Earth first!",
	"Earthshaker first!",
	"Quake and crack!",
	"They call me the Fissure Man!",
	"Ground pound!",
	"Slammin'!",
	"Chaos Dunk!",
	"Slammin'...?",
	"Echo Slam...?",
	"Stronger by an order of magnitude.",
	"I am greatly moved.",
	"My heart is pounding.",
	"Did you feel that?",
	"All fall down...",
	"Not my fault...",
	"Stop shaking...",
	"Reduce, reuse, respawn.",
	"The Earth needs me.",
	"The Earth and I rise as one.",
	"No longer will your hooves dig into my hide.",
	"This is no place for a mother.",
	"Pick a different place to raise a family next time.",
	"I'll not bow to you, Sand King, but I liked your style.",
	"Clockworks...and then it doesn't.",
	"Clock-blocked!",
	"Worship that!",
	"Respect the earth...shaker.",
	"Phantom Lancer, I hate all of you.",
	"Divided you fell.",
	"Did the earth move for you too?",
	"There may be many earths, but there's only one Earthshaker.",
	"Shake well and destroy!",
	"Storm Spirit has arrived!",
	"Ha ha! I am here!",
	"Stormy weather...",
	"You had better not start without me!",
	"Draw back the curtains, I'm here!",
	"I'm in a hurry-cane!",
	"Where's the party?",
	"Let the fun begin!",
	"I'm over here!",
	"Over here now!",
	"Here I am!",
	"Puddin' pop!",
	"Ooh, who's that handsome devil?",
	"Looking good!",
	"Get set for heavy weather!",
	"Storm Force Five!",
	"Can't breathe!",
	"I blew it...",
	"I'll fight to the last...breath...",
	"Spirit...away...",
	"You blew it!",
	"Told you a storm was coming!",
	"Blow the man down!",
	"No whining now!",
	"Admiral, but not admirable. Hm hm hm hm.",
	"Call off your little storms, Razor. They're an embarassment.",
	"You shouldn't have spit into the wind, Viper.",
	"Ha ha ha ha. Your maidenly charms were wasted on me.",
	"Antimage, you're no fun at all.",
	"I accept this honor on behalf of storms everywhere!",
	"Everyone complains about the weather... well, I'm doing something about it!",
	"When a warm front and a cold front love each other very much...a storm is born!",
	"I only want blue tangos in my dressing room!",
	"NOOOOOOOOOOOOOOOOOOOOOO!",
	"I'll save this till it's five o'clock... somewhere.",
	"Was that a spotlight? On me?",
	"Such greatness deserves to be shared.",
	"Five targets marked for death.",
	"Nyx assassin.",
	"Assassination is inevitable.",
	"My purpose is clear, my targets doomed.",
	"First blood, heheah hah heh! Nyx, Nyx.",
	"In the name of Nyx, the first assassination is complete.",
	"I skitter, thththt.",
	"On chitinous legs.",
	"I have one purpose for being.",
	"Nyx, Nyx.",
	"My words enter the mind, but not the ear.",
	"Nyx guides me.",
	"As Nyx would have it.",
	"Oh, fleshy.",
	"By Nyx.",
	"In Nyx name.",
	"Chosen of Nyx.",
	"I dig, they die.",
	"Talentless.",
	"You can't run from your thoughts.",
	"Come now, strike me.",
	"Fight, coward.",
	"Strike me, coward.",
	"I failed you, Nyx, I was so close.",
	"I am the pride of Nyx.",
	"Nyx, Nyx, Nyx, Nyx.",
	"Nyx, hehahahha.",
	"You are as dead as they come.",
	"Nyx welcomes you.",
	"Heheahah ahaha haha, Nyx, Nyx, Nyx.",
	"Nyx, Nyx, Nyx, heh heh hah.",
	"Ah, you stupid...",
	"Neither hot, nor cold, just dead.",
	"Not an easy bug to kill, but worth the effort.",
	"Hahahaha! Your books couldn't save you.",
	"Broodmotherfuh...",
	"Ahaha, the undying is dead.",
	"I despised you since the birth of my whole entire caste.",
	"Ah, impressive stinger Sand King, Very sharp, yes.",
	"Your bribe of coin is wasted on Nyx.",
	"Death and gold are linked.",
	"Aheh, Nyx on you.",
	"You've been nyxed.",
	"With my last thought, I curse you.",
	"Oh, Nyx.",
	"I am Nyx, grakillaaghraamghiah! Oi-grayoighaaah… Nyx-aaaagh...",
	"Armorless beings were not meant for life.",
	"It is not my fault. The armorless were not meant for life. Look at them.",
	"Necronomicon. Nice.",
	"Blade mail?",
	"Nyx on that.",
	"Nyx I say.",
	"Chichifchichi.",
	"Nyx chichichichichichi.",
	"Hochichchchchchchichichi.",
	"Hihchchchcichi.",
	"Nyx, heheheh.",
	"Ah, Nyx, thththt.",
	"Nyx, Nyx.",
	"For Nyx.",
	"Ah, Nyx, Nyx, Nyx, Nyx.",
	"The mysteries cannot protect themselves.",
	"Lanaya.",
	"Well that's it. The secret is out!",
	"First blood! There's nothing more mysterious until it has been spilled.",
	"A trail of clues.",
	"In pursuit of the mysteries.",
	"I am driven by secrets!",
	"Tis a secret!",
	"Psi no more!",
	"Trap set!",
	"Oh, snap!",
	"Snap!",
	"Feed me if you must.",
	"Killed by your own hand.",
	"You made a powerful enemy.",
	"You came too close to the secrets.",
	"You'll never know the mysteries.",
	"You never could keep a secret.",
	"The truth is all around you but it hides from the unworthy.",
	"For heresies unknown, the Temple decreed your death.",
	"Secretly, I admired you.",
	"The only mystery is how you lasted so long.",
	"Riki, it's no secret that you're a poor assassin.",
	"Omniknight, your continual braying had to be silenced.",
	"Oh, Spectre, we could have shared such secrets.",
	"I thought you spoke of mysteries but I see you were only confused.",
	"Phantom Assassin, you're not here for me, are you?",
	"Keeping secrets can kill you.",
	"Now you'll never know.",
	"Is that all there is?",
	"Let's keep that between us, all right?",
	"My body is a temple for which I will kill.",
	"It's no secret- I was hoping for one of these.",
	"It's an open secret, obvious to all, that this one is in the bag!",
	"Our secrets now lie bare for the whole world to see.",
	"The mysteries are safe for another day.",
	"Ha. Ha. Ha.",
	"Phantom Assassin!",
	"I'm here to blur the line between life and death.",
	"My list has five names on it.",
	"Have some blade.",
	"Were you expecting me?",
	"Unkind cut!",
	"I feel...blurry!",
	"My edges are running!",
	"I'm soft on the eye.",
	"I'm easy to overlook.",
	"You'll see less of me now.",
	"I'm an immaterial girl!",
	"There's more of me, but less to see.",
	"That went well, I think.",
	"Assassination is nature's way.",
	"Death at my hands is an honor.",
	"Gotta keep my hand in.",
	"I'm not greedy.",
	"Turnabout is foul play!",
	"Don't tell me, I'm a sight for sore eyes.",
	"Queendom come!",
	"There will be pain, there will be screaming.",
	"So begins the reign of pain.",
	"Make way for your Queen.",
	"First blood! Just a little, he he he.",
	"A path to pain.",
	"Does this hurt!",
	"A love bite!",
	"Pain builds charcter.",
	"A little knife play?",
	"Oh! I love your new piercing!",
	"Was it really that bad?",
	"Didn't like the sound of that?",
	"You were weak.",
	"I'm a strong believer in women's suffer-age.",
	"Done already?",
	"My bindings tighten!",
	"I'm a pain specialist.",
	"Did you forget your safe word?",
	"The ecstasy of agony.",
	"You hurt the ones you love.",
	"Night Stalker, you aren't the only thing that goes bump in the night.",
	"Oh, Anti-Mage, I'll make you break your vows.",
	"Crystal Maiden... are you really, I wonder?",
	"Silencer? I'd prefer a screamer.",
	"Bones and no flesh? Where's the pleasure in that?",
	"Submit to your lasy, little girl.",
	"You want me? Come get me.",
	"You can look but don't touch. Come to think of it, don't look either.",
	"Skeleton King, could you feel something for me?",
	"Your pain, my gain.",
	"What a pain in the aaaaaaaa!",
	"I'll be my own successor!",
	"I know I'm a pain, but you love me anyway.",
	"I'm in a world of pain, it's wonderful!",
	"You'll find that I'm all stick and no carrot.",
	"Bottle royale.",
	"You're simply not worthy.",
	"The pain shall set you free, ha ha ha ha ha ha ha ha ha",
	"It feels so good to be bad.",
	"The Moon Rider has arrived.",
	"Nova could use a snack.",
	"Watch over me, Goddess. It'll be a good show.",
	"First blood! For Selemene and for the Dark Moon!",
	"I'll see your entrails.",
	"Let the sky tear down the unworthy!",
	"Hungry, Nova?",
	"Die with honor, whelp.",
	"Aww. Are you not going to beg?",
	"Lost in the woods, are you?",
	"Clearly not your best.",
	"Pathetic.",
	"Not bad for a cat toy.",
	"I'll take your hoof for a trophy.",
	"No princess lives forever, Mirana.",
	"I've waited years to do that.",
	"Don't blame me for being ambitious.",
	"I would water the trees with their entrails if Selemene would smile on me.",
	"Hah! I remember when Nova tried to kill me. Good girl.",
	"Isn't that a pretty thing!",
	"Your Priestess has arrived!",
	"Tuck your tail and run, you mutt!",
	"Bullseye!",
	"Out of my way!",
	"Who spoiled that shot?",
	"Son of a...",
	"Just what are you hiding, Roshan?",
	"I could have hit Roshan with my eyes closed.",
	"Poor Roshan.",
	"Stars, take me!",
	"Lucky shot...",
	"It was not luck, but... skill!",
	"Pathetic whelp.",
	"Seeing stars?",
	"You have learned nothing.",
	"You make a fine crater.",
	"A mounted bow will always claim victory.",
	"Luna, you shouldn't get catty.",
	"Sagan has been eyeing your mount all day.",
	"If you must dominate a beast to your cause, you have already lost.",
	"And now you are kitty litter.",
	"Carl, meet Sagan.",
	"I hope no one here is allergic...to defeat.",
	"Nice kitty...very nice kitty...",
	"Nothing stirs the blood like battle. It's better than catnip!",
	"The cost of kibble.",
	"Sparkles, like the stars.",
	"I am Sand King.",
	"All flesh is sand.",
	"Sand swallow you.",
	"They'll never find your bones.",
	"I'll sand you down to nothing!",
	"Sand storm!",
	"Shuh Shuh Shuh Shuh Shuh ShuhShuh mm mm mm mm Shuh Shuh",
	"snd snd snd azzz zaza snd snd snd ah ha ha",
	"Sand!",
	"Nicely stung!",
	"Stings, don't it?",
	"On your knees!",
	"I die!",
	"Not I!",
	"Never...settle...",
	"Dust to dust...",
	"It's good to be King!",
	"Lives like grains of sand.",
	"You were expecting...Sandy Claws?",
	"What's done is done.",
	"Sand and deliver!",
	"I won't sand for this!",
	"I will show you fear in a handful of sand...",
	"All we are is sand in the wind...",
	"True horror is a verdant garden...",
	"Oh best of all possible purchases!",
	"The crown of sand has fallen...",
	"A Sandy V-V-Victory!",
	"Blink the sand from your eyes.",
	"Their annihilation is but a blink away.",
	"Eight legs and you still stumbled.",
	"What a wretched sort of sand beetle Weaver was.",
	"The wind should carry sand, not arrows.",
	"The best place on earth for you is under it.",
	"What? You didn't enjoy my dry wit?",
	"So much greenery is unnatural.",
	"The sand of silence.",
	"First blood on the sand strikes the perfect note.",
	"A passing death and nothing more.",
	"My broodcase opens.",
	"The spider comes.",
	"Mother of all evil.",
	"First blood goes to mother!",
	"The silk road beckons.",
	"Was that a twitch on my web?",
	"None shall spy the spider.",
	"My brood needs food.",
	"Mother is angry.",
	"You're in need of mothering.",
	"A mother's love.",
	"My brood hatches.",
	"What a lovely brood.",
	"Like mother, like spiders.",
	"More mouths to feed.",
	"Don't die, my darlings.",
	"Save some for mother.",
	"In my web your eyes deceive you.",
	"You feel me?",
	"My belly burns with hunger.",
	"Feeding time.",
	"I'll drink you dry.",
	"Come to mother!",
	"I'm coming for your life!",
	"My web grows stickier.",
	"You're not afraid of spiders, are you?",
	"Heh, liquified innards, my favorite.",
	"I only have eyes for you.",
	"I could kill you with five eyes closed.",
	"Sss-sss-ssslurp!",
	"Why Weave when you can spin?",
	"Night Stalker, that's a face not even a mother could love.",
	"With you gone, Earthshaker, the world is safer for my babies.",
	"Mother knows best.",
	"I'm still hungry.",
	"What would your mother say?",
	"My brood will avenge me.",
	"My eyes were bigger than my belly.",
	"These eyes cannot cry.",
	"Butterfly...delicious.",
	"Mother says no.",
	"Empty calories.",
	"You have a mother's gratitude.",
	"The threads of fate are mine to weave.",
	"The first thread is cut.",
	"Bitter pattern.",
	"Hehehcheehchessses.",
	"Checklichicklilehechiaz.",
	"Ticheticherateh.",
	"Skitter on.",
	"Clickity click.",
	"Skitter scatter!",
	"Don't mind me.",
	"Chechechheh.",
	"dhehe!",
	"You thought you had me, didn't you?",
	"nohoho.",
	"Snk nk nk scknt.",
	"Who puts their skeleton on the inside?",
	"That's no way to protect your vitals.",
	"What sort of bug are you, Assassin?",
	"Ho, snap!",
	"I hate this pattern.",
	"There's a snag in your plans.",
	"I'll avoid any further entanglements.",
	"I'll weave a brighter pattern this time.",
	"Fate weaves the threads of our lives together. Fate also wields the blade that cuts them short.",
	"Glorious radiance!",
	"No ho ho ho!",
	"Nooooho!",
	"All hail the Lord of Trolls.",
	"The strong shall eat the weak.",
	"My hate shall burn you down.",
	"Nyaheh heh, first blood, last word, I got it all.",
	"There are no innocents.",
	"These blades are too dry.",
	"Trolling for victims.",
	"I peel back your uglies.",
	"Please do feed the trolls.",
	"Here's axe in your eye.",
	"You're my trolls now.",
	"I bring out the troll in everyone.",
	"They'll do what I tell them or regret it.",
	"A nasty busyiness just got nastier.",
	"The ultimate in trolling!",
	"Killing you was the least I could do.",
	"You been trolled.",
	"Fortune favors the trolled.",
	"Your life is trunk-cated, heh hah he hah.",
	"The trolls from the hills are barely trolls at all.",
	"Do you know what I hate? You!",
	"You remind me of me. I hate you most of all!",
	"Enjoy your ban.",
	"I kill my enemies first, my allies next.",
	"I'd be better off fighting alone.",
	"Why are my allies so weak and pathetic?",
	"I can see I'll have to carry us to victory.",
	"Try not to feed.",
	"Just try not to feed.",
	"Pay the troll.",
	"You've been trolled.",
	"Go on, feed me.",
	"Trolls always get the last word.",
	"Being dead only makes me angrier.",
	"Anonymity, the friend to every troll.",
	"More of me to hate.",
	"I will kill you.",
	"Do that again, and I will kill you.",
	"Now I'm ready, to stab you.",
	"I'm not even sure why I'm so mad.",
	"Get off your ass and help me!",
	"Why aren't you helping me!",
	"Why am I so angry for no reason?",
	"Sometimes you just wake up on the wrong side of the bed.",
	"Why doesn't anybody like me?",
	"If I wanted your opinion, I wouldn't be me.",
	"It was everyone else's fault.",
	"If I had a decent team, this never would have happened.",
	"With this team, I never had a chance!",
	"Why do I always get the worst teams?",
	"I knew I should have gone to bed instead.",
	"Don't look at me. I did everything right.",
	"I'm going home.",
	"I carried us to victory!",
	"Even with this team, I managed to win.",
	"I can't get any good help.",
	"Oh, I deserve this for being so nice.",
	"What the hell is this?",
	"I'll kill you all.",
	"It is time to gut you.",
	"Mask of madness? Seriously?",
	"Mask of death? Are you kidding me?",
	"Fighting a troll only makes him grow stronger.",
	"This is all their fault.",
	"Medusa!",
	"The Gorgon!",
	"Sharpening my fangs.",
	"Gaze upon Medusa's beauty, and despair!",
	"First blood, and it came so easily.",
	"First blood -- I like to start with dessert.",
	"I know, right?",
	"None can resist!",
	"Lock eyes with a Gorgon!",
	"Gorgonzola!",
	"Let my beauty still your breath.",
	"Fetch me some mana!",
	"Behold my beauty!",
	"Oh, crap!",
	"The serpent is chastened.",
	"Stronger with every skin I shed.",
	"Ah, the wind in my serpents!",
	"Power is beauty.",
	"Power is the only beauty.",
	"So puny, I hardly had to unhinge my jaw.",
	"A kiss, and then good-night.",
	"Die, as all love dies.",
	"Don't resist the cobra, little bird.",
	"I'm surprised you lasted this long.",
	"I thought you'd last longer.",
	"I'm having a good hair day.",
	"You slither like an amateur.",
	"Meet a real snake, you eel.",
	"Snakes on a plane!",
	"I know a thing or two about working stone.",
	"Reptiles rally!",
	"Ah, Venomancer. We both traded beauty for power.",
	"We well know, Venomancer -- beauty fades, but power lasts forever.",
	"Zeus on the loose!",
	"Kiss, kiss.",
	"I shed my sssskin.",
	"Where is the justice in this?",
	"Even a severed head can bite.",
	"I'm having a bad hair day.",
	"Do I mourn for my lost loveliness? No.",
	"When I was beautiful, I never knew what I was missing.",
	"Bejeweled as a snake.",
	"Is it creepy that I have a snakeskin purse?",
	"In your face.",
	"How does failure taste?",
	"Nobody look at anybody!",
	"Victory warms the coldest heart.",
	"Failure chills the coldest heart.",
	"Find me a mirror, and I'll end it all.",
	"I come -- the venemous once.",
	"Dripping venom, I arrive.",
	"It's in my nature.",
	"Ooh, what a waste of venom.",
	"Sssss, that burns.",
	"I've been burned.",
	"My venom glands engorged.",
	"Have I tainted the well of our discourse?",
	"You were a fool to oppose me.",
	"No necromancer shall raise what the venomancer puts down.",
	"Venom beats Viper!",
	"It's all me.",
	"It's not hard.",
	"I owe it all to me.",
	"I deserve this.",
	"It's a Venomancer enhancer.",
	"I only wanted to kill...everyone.",
	"The pain. The pain!",
	"My venom sacs run empty.",
	"Oh what a burn!",
	"Like a blight, I return.",
	"I'm a perfect 10...on the pain scale.",
	"Yes, ah ha ha ha ha ha...kof!",
	"Ssstop it!",
	"First Blood is the sweetest.",
	"Get over here and help me!",
	"Hear me, I speak for the shades!",
	"I am the medium between the worlds!",
	"Suluchi-nominus-forti-cali!",
	"Au-mosu-atikanu!",
	"Beat you like a drum!",
	"Bukaaww!",
	"Bukaw, bukaw!",
	"Tastes like chicken!",
	"Moto Keyeyanna yaya, toyka yameh.",
	"Neia teia an da ka!",
	"Care for some company?",
	"This tower will fall!",
	"My serpents paralyze!",
	"I see you a future full of death!",
	"Death is not the end, but it might as well be.",
	"To the other side...and don't come back.",
	"My ancestors... welcome me.",
	"Who casts that shadow?",
	"To read the future, I need entrails!",
	"Ecstatic return!",
	"I move to my own drumbeat.",
	"Ancestors...forgive me!",
	"For our fathers, gone beyond the hills!",
	"I sense the proximity of souls...",
	"It's now or Nevermore.",
	"Shadow Fiend.",
	"Soul-collector!",
	"Need...more...souls!",
	"It's the perfect time to start a new collection!",
	"First soul swimming in First Blood sauce!",
	"First Blood...sauce for the soul.",
	"I'll take that soul if you're not using it.",
	"I'll see you in the Abysm.",
	"Never has there been such a day!",
	"All this has been for nothing?",
	"There has never been such a victory!",
	"Double damage means double damnation.",
	"I thank you from the bottom of my souls.",
	"Shadow Demon!",
	"Your old master has returned!",
	"With this blood I seal my promise of Dominion!",
	"Obey? Me?",
	"Thus do I dominate!",
	"Come into my shadow!",
	"My, how you've grown.",
	"A demon's blessing!",
	"I look after my own.",
	"Come back soon.",
	"I'll be right back!",
	"Don't wait up.",
	"That was sick!",
	"In the end, you're all mine.",
	"Just your bad luck.",
	"Cry some more.",
	"Deal with it, Anti-Mage.",
	"My cult is leaderless!",
	"That's it: You're out of the cult.",
	"Summon forth, fifth, and sixth.",
	"Who toys with demons will find himself toyed with.",
	"A blinding light dispels my shadow!",
	"All creation swept into my shadow!",
	"I could hear your caterwauling from clear out on the rim.",
	"Their sanity I'll shatter, their dreams of conquest I'll destroy.",
	"The blood sun rises.",
	"Last warning.",
	"Your future is grim.",
	"My mind blots yours out.",
	"Your attention please.",
	"Time out for you.",
	"Take some time to think it over.",
	"Think it over.",
	"Orb on.",
	"Orb off.",
	"My wings beat with the rhythms of eternity.",
	"Lifted up on a mad wind.",
	"Bad luck.",
	"I warned you.",
	"That sharp pain you felt was my intellect.",
	"I was only indirectly responsible.",
	"The worst is still to come.",
	"Well, well, if it isn't Auntie Mage.",
	"I heard you were heavy but I found you not so.",
	"Hard carry? I hardly cared.",
	"My wings, my heart, no longer beat.",
	"This changes nothing.",
	"Worse things than me wait in the wings.",
	"A second scepter.",
	"Three scepters.",
	"Quad scepter!",
	"Another null talisman.",
	"Can't have too many of these.",
	"The Destroyer is destroyed.",
	"At last my existence has meaning.",
	"Keep your eye on my horn!",
	"Behold the horn of Magnus!",
	"Horn calls to horn and it begins!",
	"Ha ha, the thunder of my hooves!",
	"By the gleam of my horn!",
	"Behold the horn!",
	"Yes, the thunder you hear is my hooves.",
	"You shall perish upon my horn.",
	"Preparing for a goring.",
	"All of you gather round, ha ha!",
	"Quit squirming!",
	"Ah, kebab!",
	"You need some onions in between you!",
	"Mind if I horn in? Ha ha!",
	"Rah! How many did I get?",
	"Hop on my pike!",
	"This pike is for you!",
	"This is bullshit!",
	"Aw, shit!",
	"Are you kidding me?",
	"Accustom yourself to loss. It suits you.",
	"The horn that gored you was precious beyond all measure.",
	"I faced down a volcano. What made you think you stood a chance?",
	"What do you mean I'm not your type?",
	"Quit playing hard to get.",
	"Is it too late to court?",
	"Too chilly for my tastes, maiden.",
	"I prefer the talkative types, Ranger.",
	"I am sorry I hurt you, creature. But not your rider.",
	"Only I shall shake the earth from now on.",
	"Too many legs make for a messy gait.",
	"I'll not be cowed by any fish.",
	"You're no match for me, fishfingers!",
	"You're no match for me, fishstick!",
	"I have tarter sauce for people like you.",
	"I could show you the meaning of pain, oh Queen.",
	"Why are all the good ones dead, Death Prophet?",
	"Windrunner, you are always running through my mind.",
	"I survived an eruption but died to this?",
	"Poachers! Bastards.",
	"Touch my horn and be cursed.",
	"They can hurt my body but not my pride.",
	"Was it something I said?",
	"It will take more than death to discourage me.",
	"I tell you what. You touch my horn, I break your face.",
	"No, I blame no one who covets my horn. But to desire more than sight of it is a guarantee of death.",
	"Compared to my horn, all precious items are cheap.",
	"Scepter is no horn, but I prize it nonetheless.",
	"A bounty which my matriarch will prize!",
	"My homelands, lost forever now.",
	"Was there ever any doubt?",
	"Huh?",
	"I quiver with anticipation!",
	"Drow Ranger!",
	"I'm notched, I'm taut, I'm ready to fly!",
	"Death comes silently.",
	"Rangers with candy.",
	"Weep not for me.",
	"It was worth it.",
	"Blown out on a cold wind.",
	"Bullseye!",
	"You die alone.",
	"Chill out!",
	"I thought they warned you not to speak with rangers.",
	"The lanes are lined with the likes of you.",
	"You were too noisy to live.",
	"Don't quit your day job, Luna.",
	"I heard your bones rattle with fear.",
	"The hot shot, got shot.",
	"Silly doe.",
	"That's quite the arrow, Mirana.",
	"Enchantress, will you be prancing our enemy to death?",
	"Follow me into the forest shade, and none may spy on us.",
	"Weep some more...",
	"Tastes so sweet...",
	"Fate is so cruel.",
	"I'll need a hand free for this.",
	"Techies!",
	"We're Techies Demolitions! Hey, how you doing?",
	"Techies Demolitions! We put the tech in tech-nically we meant to do that.",
	"If you want explosions. Accept no substitutes!",
	"I am Squee! I'm Spleen! And I'm Spoon!",
	"They call me Squee! They call me Spleen! They don't know I'm here. Who said that?",
	"Measurements made. Bombs built. Poweder's dry. Okay, let's blow something up!",
	"First blood! Start with a bang!",
	"Huh! Heh hehe he he he he he he he he. What're you giggling about?",
	"See! Fore!",
	"Did we put the right fuse on that one?",
	"Planted.",
	"Planted!",
	"Planted! Like a tree.",
	"Pretty! Yeah!",
	"I heard something!",
	"Bang!",
	"Kaboom!",
	"I wonder what we'll catch!",
	"The traps work! Told you!",
	"Suicide squad! Attack!",
	"Nice knowing ya!",
	"Bye! Bye! Bye.",
	"I regret nothing! I do.",
	"Oh crap!",
	"Whoopsie!",
	"Bomb has been planted.",
	"Aw, just look at it. Nice.",
	"There's a good little mine.",
	"Beautiful.",
	"Just beautiful.",
	"So beautiful.",
	"Yes you're a good little mine. Yes you are.",
	"Loud noises!",
	"My favorite!",
	"Ah! I can't believe it worked!",
	"Eureka!",
	"Huh. We sure bombed that.",
	"Bomb has been defused. Darn!",
	"Premature detonation. Don't worry--happens to a lot of explosives.",
	"A mine is a terrible thing to waste.",
	"I was told there'd be a mushroom cloud!",
	"My mind is exploding with ideas. Not literally I hope!",
	"Hoh! I'm brilliant. You are?",
	"Didn't mean to hurt ya! I did.",
	"You died for science!",
	"Next time wear safety goggles!",
	"Now that's what I call a success.",
	"So much for peaceful applications.",
	"Proper safety is really boring.",
	"Hey. You okay?",
	"And that is why I wake up in the morning!",
	"That's a nice crater you've got there.",
	"They're going to have to glue you back together! Yeah, in Hell!",
	"Everybody make it back? I think so. Yep. Who keeps talking?",
	"So what'd you do with your break? Uh, I think I was dead. Oh.",
	"Why did they kill us? Yeah, that's our job. W-what?",
	"Interesting. The alloy appears to be-- Shut up, it's magic!",
	"Shitty wizard. Language!",
	"Counter-Techies win.",
	"Can I come out now?",
	"Who said we couldn't count to three, huh?",
	"I am the Plague Mage.",
	"Behold the Pope of Pestilence.",
	"Sweet spoilage.",
	"Greet the reaper!",
	"I reap your life.",
	"Die young and leave a purulent corpse.",
	"The stench of death is upon you.",
	"You taste your own rotting tongue.",
	"Rot starts at the head.",
	"Oh Pudge, I just can't hate you.",
	"What a pleasure to be on your team, Pudge.",
	"You're a dirty, dirty knight.",
	"Kill is the cure!",
	"May the worms that feed on me sicken and die.",
	"Return of the ragin' contagion.",
	"The plague vector returns.",
	"An ounce of prevention shan't stop me.",
	"You'll rot longer than you live.",
	"An ounce of putrefaction is worth a pound of cure.",
	"What do you mean, cheer up? I'm quite cheerful.",
	"Oh, this is sick!",
	"I feel ill...in a good way.",
	"Damn child-proof cap!",
	"It's all gone rotten.",
	"To the victor, the spoiled.",
	"Ugh... Regeneration...",
	"I am Tidehunter.",
	"Time and Tidehunter wait for no man.",
	"Amphibious assault!",
	"You swim against the tide.",
	"You can't hide from the tide.",
	"Think of it as caviar.",
	"Ravaged!",
	"You look ravaged.",
	"I'm hungry enough to eat a plankton.",
	"I could eat a diatom.",
	"I could eat a krill.",
	"I could eat an anchovy.",
	"I could eat a sea cucumber.",
	"I could eat a seagrape.",
	"I could eat a seahorse.",
	"I could eat a nautilus.",
	"I could eat an eel.",
	"I could eat a jellyfish.",
	"I could eat a mullet.",
	"I'm so hungry I could eat a mackerel.",
	"I could eat a giant isopod.",
	"I could eat a tubeworm.",
	"I could eat a manatee.",
	"I could eat an oarfish.",
	"Ha ha! I could eat a walrus.",
	"I'm hungry enough to eat a manta ray.",
	"I could eat a shark.",
	"I could eat a whale shark.",
	"I could eat a blue whale.",
	"I could eat a colossal squid.",
	"I could eat a plesiosaur.",
	"I'm stuffed!",
	"I hang a coral wreath on your grave.",
	"Rip tide!",
	"I bring sad tidings: You're dead!",
	"Ha ha ha! Women and children and Kunkka first!",
	"Tidewracked!",
	"An anchor around my neck!",
	"I sleep with the fishes.",
	"Kunkka, you're not my admiral.",
	"Kunkka, I thought I left you on the bottom of the sea.",
	"I'll have my vengeance yet, Kunkka!",
	"Kunkkaaaaaaa!",
	"The admirable Admiral dies like a dog!",
	"Die in slime, Admiral Mouthbreather!",
	"Where's your fleet now, Kunkka?",
	"I always pitied you, Morphling, for having to carry Kunkka's ships.",
	"Ah, sweet Siren, if only you'd steered Kunkka onto the rocks.",
	"You should put your fire to work burning up Kunkka's ships.",
	"Why fire your arrows at me when Kunkka's sails need burning?",
	"Why fight me, Slardar? Together we could have brought Kunkka to the bottom.",
	"You could have given Kunkka some pointers in how to die nobly.",
	"You were a commanding presence, which is more than I can say for Kunkka.",
	"Puck, you taste as bad as Kunkka's boot.",
	"Take a bath, Axe. You smell worse than Kunkka!",
	"Your metal jacket sank you faster than one of Kunkka's ships.",
	"You went down like Kunkka's ship.",
	"Next time, Weaver, let Kunkka give you lessons in scuttling.",
	"He abandoned this plane faster than Kunkka abandoned his fleet.",
	"Did you think I'd blunder? You must have mistaken me for Kunkka.",
	"The red tide comes.",
	"Fresh id good...unless we're talking water.",
	"Got to keep moving, or I suffocate.",
	"Who needs a big brain when you've got teeth like mine?",
	"By Maelrawn the Tentacular, the Lurker in the Whirlpool, may my enemies be sucked down in spirals!",
	"Blood in the water, time to feed!",
	"Ha ha ha! A rogue wave carries me back!",
	"That was good of you.",
	"And so it falls to me.",
	"Someone requires my protection!",
	"The seasons wheel past in a blur.",
	"Thoughts cross my mind as the sun crosses the sky.",
	"The time has come, and soon will be gone.",
	"First blood! From a deep-cut notch, the red sap flows.",
	"Trees are not so good with motion, you know.",
	"Are you lost?",
	"Trees can be ferocious if provoked.",
	"A clouting is called for.",
	"Farewell, trees.",
	"Hmm. Where's a tree when you need one.",
	"How forgetful of me. We need a tree.",
	"Can't see the forest for the trees.",
	"Nature is not always kind.",
	"Come into my shade.",
	"A bit more bark, if you please.",
	"Make like a tree, and stay put.",
	"Take root. Go on, take it!",
	"They say my bark is worse than my bite. I wonder what that means.",
	"Hmm? I feel a new branch coming in.",
	"Is it weird that I drink with my feet?",
	"Where the path branched, you chose unwisely.",
	"That will teach you to assail the defenseless.",
	"A little respect for the forest, please.",
	"A tree killed you. A tree!",
	"I protected you to a pulp.",
	"Someone put a bounty on a tree?",
	"Keep your hot little hands away from me, Lina.",
	"By MY bark!",
	"That's enough now, little tree.",
	"You may be the only one here who is slower than I.",
	"You were nasty, brutal, and most of all short.",
	"So swift a life.",
	"What a lovely day.",
	"Think me not ponderous, merely pondering.",
	"Hmm. Back to war.",
	"Life becomes death becomes new life. As it should be.",
	"This lets me move how fast?",
	"Sheep... stick?",
	"One can never have too many branches.",
	"Sorry, friend.",
	"That was rude of me.",
	"Run? I am running!",
	"Oh! My friends are here.",
	"Now come the axes and the fire.",
	"I'm really freaking out.",
	"What wonders will I see this day?",
	"I am Rubick, the Grand Magus.",
	"First blood? What is this? I came here to be tested!",
	"That should take the edge off!",
	"So that's how it's done!",
	"This should come in handy!",
	"My turn now!",
	"How peculiar!",
	"I am no thief, I merely borrow.",
	"There are none who cannot be mimicked.",
	"Fun ultimate!",
	"I-I've forgotten something!",
	"I should have written that spell down.",
	"Memory is an imperfect vessel.",
	"A taste of your own medicine!",
	"Ha! That was terrible.",
	"Oh. I hope no one saw that.",
	"Still a magus, yet now much grander!",
	"I think I'll flex a bit.",
	"Well done. But not well enough.",
	"You're wasting talent!",
	"What did you hope to gain from that?",
	"Who is the ultimate magus? That's right, I am.",
	"Poor show, Arsenal Magus.",
	"Even the Arsenal Magus falls before my magic.",
	"Invoker, your ego is as big as the crater I leave you in.",
	"Your name offends me.",
	"So you keep a book for your spells? Good idea.",
	"Invoker now, eh? No longer the Arsenal Magus?",
	"Show some ambition!",
	"Apply yourself!",
	"I'm coming, friends! Wait for me!",
	"Your attempt was pathetic.",
	"So much destroyed for so little.",
	"Such talent! Such sorceries! Such a pleasure!",
	"The Age of Ice begins!",
	"Ancient Apparition!",
	"Hail of death!",
	"Sharded shrapnel!",
	"No shard feelings. Hm hm hm hm hm hm hm.",
	"Ice bejewels your corpse.",
	"Crystal Maiden, you dare cross ice with me?",
	"Now is the winter of your disembowelment.",
	"Hoary frost upon you!",
	"Behold the apparition.",
	"Set loose the fog of war.",
	"Ancient but hardly frail.",
	"Cold shard cash.",
	"Age before beauty.",
	"I look again upon the cold light of day.",
	"Colder than hell's heart, I return.",
	"One day, ice will cover these lands, and it will be as if this war never happened.",
	"My spirit may be locked in ice, but my rage still burns.",
	"I'm Rizzrack. Don't touch me.",
	"I'm not a lumberjack! This. This is personal.",
	"There are trees everywhere!",
	"First blood! I cut you, and I split you, and I killed you! Ha ha ha ha ha ha!",
	"Spin! Cut! Shred!",
	"Stay away from me!",
	"Oh God I think I'm going to be sick.",
	"I'll cut everyone!",
	"It slices, it dices!",
	"Ah! Well, that was fun.",
	"They're gonna get me.",
	"Oh no, no no now what?",
	"I'm trapped. Trapped!",
	"The forest ain't safe!",
	"Looking sharp! Crazy sharp.",
	"I'd hack you down again if I could!",
	"You don't get to win. I get to win!",
	"You mad? Cuz I am! Hahah!",
	"Nobody takes me seriously.",
	"Your friends are next, Prophet.",
	"Trees do have a way of dying around me!",
	"Finally, I haven't slept in weeks.",
	"Not listening. Not listening. Not listening.",
	"Not so tough without your friends, are you?",
	"Why are you so perky, Enchantress? Can't you see what's happening?",
	"Ah, Dark Seer. Finally someone who appreciates a wall without padding.",
	"Feeling peaceful!",
	"Dammit!",
	"Oh not the trees! No!",
	"Ah nuts.",
	"What? What-what happened?",
	"Oh it's all so clear to me now.",
	"Dammit.",
	"Blink dagger? I don't need to blink!",
	"Branch?",
	"Mm god I hate trees.",
	"Never know! You just never, never know.",
	"Keep your hands to your self!",
	"Oh ho ho ho ho ho! No.",
	"They can't kill me. Nobody can.",
	"No escape! No escape! They they're gonna find me! They'll get me I'm telling you I know it they cz vz mm!"
];
